### ISSUE TITLE
Being used maliciously?

### ISSUE THREAD

**Issue by ted-marozzi** [mysterioustrousers/FakeContacts#1]
I received a suspicious missed call from a name.lastname@icloud.com, upon googling it took me here. I was wondering if people may be using this to generate contacts to scam people. Wanted to let you know although its probably just coincidence.

**Comment by atomkirk** [comment]
What did you google?

**Comment by TedMarozzi** [comment]
I googled the exact email nothing else. Obviously they were filled in with an actual first name and last name that appears on your code, i wasn’t sure if it was okay to disclose the exact email incase it was a real persons icloud?

**Comment by TedMarozzi** [comment]
Hi,
i googled rebecca.kara@icloud.com.
